---
# tasks file for mysql
#
- name: "Apt update repo"
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: "Installing mysql-server"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ ubuntu22_04_pkgs }}"

- name: "Starting mysql-server service"
  ansible.builtin.systemd:
    name: "mysql"
    state: started
    enabled: yes
