---
- name: "Update dnf repository"
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: "Installing mysql server"
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ centos_8_5_pkgs }}"

- name: "Starting mysql-server service"
  ansible.builtin.systemd:
    name: "mysqld"
    state: started
    enabled: yes
